@echo off
setlocal enabledelayedexpansion

REM Always operate on the repository root, regardless of where this is invoked from
cd /d "%~dp0"

set FILE_NAME=assessment-cc-agentic-devops-aws-kubernetes-sr-01.zip
set ZIP_FILE_FULL_PATH=%CD%\!FILE_NAME!

REM tar.exe (bsdtar) ships with Windows 10 1803+. Unlike Compress-Archive it does
REM not skip hidden items, which is required because .git/ and .ci-evidence/ are
REM graded artifacts.
where tar.exe >nul 2>&1
if errorlevel 1 (
    echo [31mERROR: tar.exe not found.[0m
    echo tar.exe ships with Windows 10 build 17063 and later and is required here,
    echo because PowerShell's Compress-Archive silently omits hidden files such as .git.
    echo Please update Windows, or create the zip with 7-Zip / WSL instead.
    exit /b 1
)

REM Remove generated folders
echo Removing unnecessary autogenerated folders and files

REM Javascript libraries and frameworks
rmdir /s /q codebase\rdicidr-0.1.0\node_modules 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\dist 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\build 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\out 2>nul
rmdir /s /q codebase\rdicidr-0.1.0\tmp 2>nul

echo [32mUnnecessary autogenerated folders and files removed successfully[0m

echo Compressing challenge into !FILE_NAME!

REM NOTE: .git/, .github/, .chat-history/, .ci-evidence/ and evidence/ are all
REM graded artifacts and MUST be included. Do not add a .git exclude here.
del /q "!ZIP_FILE_FULL_PATH!" 2>nul

tar.exe -a -c -f "!ZIP_FILE_FULL_PATH!" ^
    --exclude=!FILE_NAME! ^
    --exclude=*/node_modules/* ^
    --exclude=node_modules ^
    --exclude=.DS_Store ^
    .

if errorlevel 1 (
    echo [31mERROR: archive creation failed.[0m
    exit /b 1
)

echo [32mCompression complete: !ZIP_FILE_FULL_PATH![0m

REM ---------------------------------------------------------------------------
REM Self-check: the submission is graded from these paths. Fail loudly if any of
REM them did not make it into the archive.
REM ---------------------------------------------------------------------------
echo.
echo Verifying submission contents...

set FAILED=0

REM tar.exe stores members with a leading "./", so the "/" prefix on each pattern
REM keeps "/evidence/" from falsely matching "./.ci-evidence/".
call :check ".git/            (commit history)"       "/.git/"
call :check ".github/workflows/ (CI pipeline)"        "/.github/workflows/"
call :check ".chat-history/   (AI interaction logs)"  "/.chat-history/"
call :check ".ci-evidence/    (pipeline run records)" "/.ci-evidence/"
call :check "evidence/        (k8s + PR + version)"   "/evidence/"

tar.exe -tf "!ZIP_FILE_FULL_PATH!" | findstr /c:"node_modules" >nul 2>&1
if errorlevel 1 (
    echo   [32mPASS[0m  node_modules excluded
) else (
    echo   [31mFAIL[0m  node_modules leaked into the archive
    set FAILED=1
)

echo.
if !FAILED! neq 0 (
    echo [31mSubmission is INCOMPLETE. Create the missing directories and re-run this script.[0m
    exit /b 1
)

echo [32mSubmission looks complete: !FILE_NAME![0m

timeout /t 2 /nobreak >nul

exit /b 0

:check
tar.exe -tf "!ZIP_FILE_FULL_PATH!" | findstr /c:%~2 >nul 2>&1
if errorlevel 1 (
    echo   [31mFAIL[0m  %~1  ^(missing from archive^)
    set FAILED=1
) else (
    echo   [32mPASS[0m  %~1
)
goto :eof
