#!/bin/bash
set -euo pipefail

# Color Variables
GREEN='\033[0;32m'
RED='\033[0;31m'
WHITE='\033[1;37m'
NC='\033[0m'

# Always operate on the repository root, regardless of where this is invoked from
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_ROOT"

FILE_NAME="assessment-cc-agentic-devops-aws-kubernetes-sr-01.zip"
ZIP_FILE_FULL_PATH="$REPO_ROOT/$FILE_NAME"

# Remove generated folders
echo -e "${WHITE}Removing unnecessary autogenerated folders and files...${NC}"

# Javascript libraries and frameworks
rm -rf codebase/rdicidr-0.1.0/node_modules \
       codebase/rdicidr-0.1.0/dist \
       codebase/rdicidr-0.1.0/build \
       codebase/rdicidr-0.1.0/out \
       codebase/rdicidr-0.1.0/tmp

echo -e "${GREEN}Unnecessary autogenerated folders and files removed successfully${NC}"

echo -e "${WHITE}Compressing challenge into $FILE_NAME...${NC}"

# Build the archive outside the tree so it can never capture itself, then move it in.
# NOTE: .git/, .github/, .chat-history/, .ci-evidence/ and evidence/ are all graded
# artifacts and MUST be included. Do not add a '*.git*' exclude here.
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

rm -f "$ZIP_FILE_FULL_PATH"
zip -rq "$TMP_DIR/$FILE_NAME" . \
  -x '*/node_modules/*' \
  -x 'node_modules/*' \
  -x '*/.DS_Store' \
  -x '.DS_Store'

mv "$TMP_DIR/$FILE_NAME" "$ZIP_FILE_FULL_PATH"

echo -e "${GREEN}Compression complete: $ZIP_FILE_FULL_PATH${NC}"

# ---------------------------------------------------------------------------
# Self-check: the submission is graded from these paths. Fail loudly if any of
# them did not make it into the archive.
# ---------------------------------------------------------------------------
echo -e "\n${WHITE}Verifying submission contents...${NC}"

LISTING="$(unzip -l "$ZIP_FILE_FULL_PATH")"
FAILED=0

check() {
  local label="$1" pattern="$2"
  if echo "$LISTING" | grep -qE "$pattern"; then
    echo -e "  ${GREEN}PASS${NC}  $label"
  else
    echo -e "  ${RED}FAIL${NC}  $label  (missing from archive)"
    FAILED=1
  fi
}

# NOTE: patterns are matched against `unzip -l` output, where the path is
# preceded by whitespace. Anchoring with ^ would match the size column instead.
check ".git/            (commit history)"        '[[:space:]]\.git/'
check ".github/workflows/ (CI pipeline)"         '[[:space:]]\.github/workflows/'
check ".chat-history/   (AI interaction logs)"   '[[:space:]]\.chat-history/'
check ".ci-evidence/    (pipeline run records)"  '[[:space:]]\.ci-evidence/'
check "evidence/        (k8s + PR + version)"    '[[:space:]]evidence/'

if echo "$LISTING" | grep -q 'node_modules'; then
  echo -e "  ${RED}FAIL${NC}  node_modules leaked into the archive"
  FAILED=1
else
  echo -e "  ${GREEN}PASS${NC}  node_modules excluded"
fi

echo ""
if [ "$FAILED" -ne 0 ]; then
  echo -e "${RED}Submission is INCOMPLETE. Create the missing directories and re-run this script.${NC}"
  exit 1
fi

echo -e "${GREEN}Submission looks complete: $FILE_NAME${NC}"

sleep 2

exit 0
